name: dmft
channels:
  - conda-forge
dependencies:
  - python=2.7.15
  - pip=20.1.1
  - setuptools=44.0.0
  - numpy=1.16.5
  - scipy=1.2.0
  - gfortran_osx-64
  - mpich
  - mpi
  - libblas
  - liblapack
  - gsl
  - fftw
  - pip:
      - requests==2.27.1
